steps:
  - command:
      - "pip install -r requirements.txt"
      - "python montecarlopi.py > pi.txt"
    artifact_paths: "./pi.txt"
    plugins:
      - docker#v3.5.0:
          image: "python:3.8-slim"
