steps:
  - command:
      - "pip install -r requirements.txt"
      - "python montecarlopi.py > pi.txt"
      - "enviere"
    retry:
      automatic: true
      limit: 2
    artifact_paths: "./pi.txt"
    plugins:
      - docker#v3.5.0:
          image: "python:3.8-slim"
          always-pull: true
          environment:
            - "VARIABLE=uno"
